// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyoC8bClygYhRrxedxK6vXMqOaOha02_w',
    appId: '1:703670720492:web:00bb5143cce39f1539d2c9',
    messagingSenderId: '703670720492',
    projectId: 'chat-app-9dc58',
    authDomain: 'chat-app-9dc58.firebaseapp.com',
    storageBucket: 'chat-app-9dc58.firebasestorage.app',
    measurementId: 'G-1NSNC83HDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe7pQcmPx0DMR2aaoqqO9jnsoWOmkY9uU',
    appId: '1:703670720492:android:bb2be2447eacdc6339d2c9',
    messagingSenderId: '703670720492',
    projectId: 'chat-app-9dc58',
    storageBucket: 'chat-app-9dc58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNbWoMy7bXbZlOnj6WuBBy9FJn13uwSTg',
    appId: '1:703670720492:ios:2972b33955f758a439d2c9',
    messagingSenderId: '703670720492',
    projectId: 'chat-app-9dc58',
    storageBucket: 'chat-app-9dc58.firebasestorage.app',
    iosBundleId: 'com.example.chatWithMeNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNbWoMy7bXbZlOnj6WuBBy9FJn13uwSTg',
    appId: '1:703670720492:ios:2972b33955f758a439d2c9',
    messagingSenderId: '703670720492',
    projectId: 'chat-app-9dc58',
    storageBucket: 'chat-app-9dc58.firebasestorage.app',
    iosBundleId: 'com.example.chatWithMeNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyoC8bClygYhRrxedxK6vXMqOaOha02_w',
    appId: '1:703670720492:web:a95d2f069601d03039d2c9',
    messagingSenderId: '703670720492',
    projectId: 'chat-app-9dc58',
    authDomain: 'chat-app-9dc58.firebaseapp.com',
    storageBucket: 'chat-app-9dc58.firebasestorage.app',
    measurementId: 'G-TMJM2HBVY5',
  );
}
